# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_choice_choice_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_subject',
            field=models.CharField(default='Sin tema', max_length=50),
        ),
    ]
